### PR TITLE
implement Lineage REST calls

### PR DESCRIPTION
**Pull request by AnalyticJeremy**
This PR resolves issue #68 by adding support for the Lineage REST API calls:
- GET /atlas/v2/lineage/{guid}
- GET /atlas/v2/lineage/{guid}/next/

### CODE REVIEW

**Comment by AnalyticJeremy** [comment]
Thank you, sir, for your consideration of this humble pull request.

**Comment by wjohnson** [comment]
Love it, @AnalyticJeremy !  I would ask for only one change.

Would you be able to move `get_entity_next_lineage` to the PurviewClient class instead of AtlasClient?  `get_entity_next_lineage` is not implemented in [Apache Atlas](http://atlas.apache.org/api/v2/resource_LineageREST.html) and I'm trying to keep AtlasClient focused on just the features implemented in Atlas.

**Comment by AnalyticJeremy** [comment]
@wjohnson - I moved `get_entity_next_lineage` to the `PurviewClient` class.

**Comment by wjohnson** [comment]
Thank you @AnalyticJeremy for your amazing contribution!  This is going to help a Microsoft team based in Italy with some of their customer work!

**Pull request merged**
